# Generated by Django 5.0.6 on 2024-06-05 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RentaCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_comp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='carModel',
            fields=[
                ('brand', models.CharField(max_length=20)),
                ('Owners', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.owner')),
                ('rentacar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='home.rentacar')),
            ],
        ),
    ]
