# Generated by Django 5.0.6 on 2024-06-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='Owners',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='rentacar',
        ),
        migrations.DeleteModel(
            name='owner',
        ),
        migrations.DeleteModel(
            name='carModel',
        ),
        migrations.DeleteModel(
            name='RentaCar',
        ),
    ]
