# Generated by Django 5.0.6 on 2024-06-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_remove_carmodel_owners_remove_carmodel_rentacar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('highest_education', models.TextField()),
                ('school_name', models.CharField(max_length=30)),
                ('field', models.CharField(max_length=30)),
                ('work_experience', models.TextField()),
                ('awards', models.TextField()),
                ('skills', models.TextField()),
                ('languages', models.TextField()),
                ('hobbies', models.TextField()),
                ('about', models.TextField()),
            ],
        ),
    ]
