# Generated by Django 5.0.6 on 2024-06-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='highest_education',
            field=models.CharField(max_length=70),
        ),
    ]
