# Generated by Django 5.0.6 on 2024-06-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_myblog_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
