# Generated by Django 5.0.6 on 2024-06-03 19:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_likedmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='detail',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LikedMovie',
        ),
    ]
