# Generated by Django 5.0.6 on 2024-06-03 20:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movies_detail_delete_likedmovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='detail',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
