# Generated by Django 5.0.6 on 2024-06-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movies_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='add image'),
        ),
    ]
