# Generated by Django 5.0.6 on 2024-06-05 08:27

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movies_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='add image'),
        ),
        migrations.CreateModel(
            name='WriteComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter', models.CharField(max_length=20, verbose_name='Name')),
                ('comment_content', ckeditor.fields.RichTextField(verbose_name='content')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movies.movies', verbose_name='movie')),
            ],
        ),
    ]
